### ISSUE TITLE
Panic: runtime error: slice bounds out of range [2:0]

### ISSUE THREAD

**Issue by wwwAndries** [vitwit/matic-jagar#11]
matic-jagar with this runtime error: slice bounds out of range [2:0]

goroutine 39 [running]:
github.com/vitwit/matic-jagar/targets.CurrentEthBalance(0xc000000000, 0x3d, 0x0, 0x0000ac, 0x3, 0x885bd0, 0xe, 0xc0002eee40, 0x2, 0x2, ...)
       ~/matic-jagar/targets/bor_current_balance.go:35 +0xcbf
github.com/vitwit/matic-jagar/targets.targetRunner.Run(...)
        ~/matic-jagar/targets/targets.go:26
main.main.func1(0xb000c0, 0xc000000000, 0x90df20, 0xc00000000, 0x881e4f, 0x4, 0xc000000000, 0x3d, 0x0, 0x8819ac, ...)
        ~/matic-jagar/main.go:44 +0x123
created by main.main
        ~/matic-jagar/main.go:38 +0x418

**Comment by PrathyushaLakkireddy** [comment]
@wwwAndries, we are looking into this issue. Will update the code soon.
Thank you!.

**Comment by PrathyushaLakkireddy** [comment]
We have made a new release which also fixes this issue, can you please look into that.
Thank you @wwwAndries,

**Comment by wwwAndries** [comment]
It's running fine now after updating to version 0.3, thanks @PrathyushaLakkireddy
